{
  parserClass="nl.abbyberkers.lilypond.language.parser.LilypondParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Lilypond"
  psiImplClassSuffix="Impl"
  psiPackage="nl.abbyberkers.lilypond.language.psi"
  psiImplPackage="nl.abbyberkers.lilypond.language.psi.impl"

  elementTypeHolderClass="nl.abbyberkers.lilypond.language.psi.LilypondTypes"
  elementTypeClass="nl.abbyberkers.lilypond.language.psi.LilypondElementType"
  tokenTypeClass="nl.abbyberkers.lilypond.language.psi.LilypondTokenType"

  tokens = [

  ]
}

// notes
// - all <...>_IDENTIFIERs can be replaced with SCM_IDENTIFIER. Semantics don't matter for our purposes for now.
//   If they ever do, see scan_scm_id in LilyPonds lexer.ll and try_special_identifiers in their parser.yy.

lilypondFile ::= (toplevel_expression | BLOCK_COMMENT | LINE_COMMENT)*

private toplevel_expression ::= version
                      | assignment
                      | header_block
                      | book_block
                      | bookpart_block
                      | scheme_identifier_lily /*BOOK_IDENTIFIER*/
                      | score_block
                      | composite_music
                      | full_markup
                      | full_markup_list
                      | SCM_START /*SCM_TOKEN*/
                      | scheme_expression /*embedded_scm_active*/
                      | output_def
                      | include
                      | command

version ::= VERSION_COMMAND string_lit

command ::= BACKSLASH SYMBOL

include ::= INCLUDE_COMMAND string_lit

basic_music ::= scheme_expression /* music_function_call */
              | repeated_music
              | alternative_music
              | music_bare
              | LYRICSTO_COMMAND simple_string lyric_mode_music
              | LYRICSTO_COMMAND simple_string EQUALS simple_string lyric_mode_music

contextable_music ::= BAR
                    | basic_music
                    | pitch_as_music
                    | event_chord

contexted_basic_music ::= context_prefix ((contextable_music new_lyrics?) | contexted_basic_music)

composite_music ::= basic_music new_lyrics?
                  | contexted_basic_music

music_bare ::= mode_changed_music
             | scheme_identifier_lily /*MUSIC_IDENTIFIER*/
             | grouped_music_list
             | relative_music

relative_music ::= RELATIVE_COMMAND pitch? composite_music

grouped_music_list ::= simultaneous_music
                     | sequential_music

repeated_music ::= REPEAT_COMMAND simple_string unsigned_integer music
                 | REPEAT_COMMAND simple_string unsigned_integer music alternative_music

alternative_music ::= ALTERNATIVE_COMMAND basic_music

simultaneous_music ::= SIMULTANEOUS_COMMAND braced_music_list
                     | MULTI_VOICE_START music_list MULTI_VOICE_END

sequential_music ::= SEQUENTIAL_COMMAND braced_music_list
                   | braced_music_list

simple_music ::= event_chord
               | music_property_def
               | context_change

tempo_event ::= TEMPO_COMMAND steno_duration EQUALS tempo_range
              | TEMPO_COMMAND (str | scheme_expression) steno_duration EQUALS tempo_range
              | TEMPO_COMMAND (str | scheme_expression)

new_lyrics ::= (ADDLYRICS_COMMAND optional_context_mods lyric_mode_music)+

braced_music_list ::= LEFT_BRACE music_list RIGHT_BRACE

// TODO (music_embedded | error)* parser recovery?
music_list ::= (music_embedded)*

music ::= BAR
        | music_assign
        | pitch_as_music
        | lyric_element_music

music_assign ::= simple_music
               | composite_music

pitch_as_music ::= pitch_or_music

music_embedded ::= music
                 | post_event
                 | scheme_expression lyric_element_music?/* music_embedded_backup | music_embedded_backup "(backed-up?)" lyric_element_music*/
                 | duration post_events

optional_id ::= (EQUALS simple_string)?

lyric_mode_music ::= grouped_music_list
                   | scheme_identifier_lily /*MUSIC_IDENTIFIER*/
                   | command

mode_changed_music ::= mode_changing_head grouped_music_list
                     | mode_changing_head_with_context optional_context_mods grouped_music_list

mode_changing_head ::= NOTEMODE_COMMAND
                     | DRUMMODE_COMMAND
                     | FIGUREMODE_COMMAND
                     | CHORDMODE_COMMAND
                     | LYRICMODE_COMMAND

mode_changing_head_with_context ::= DRUMS_COMMAND
                                  | FIGURES_COMMAND
                                  | CHORDS_COMMAND
                                  | LYRICSS_COMMAND

context_change ::= CHANGE_COMMAND simple_string EQUALS simple_string

property_operation ::= simple_string EQUALS scalar
                     | UNSET_COMMAND simple_string
                     | OVERRIDE_COMMAND property_path EQUALS scalar
                     | REVERT_COMMAND property_path

context_prefix ::= CONTEXT_COMMAND str optional_id optional_context_mods
                 | NEW_COMMAND str optional_id optional_context_mods

optional_context_mods ::= context_modification_mods_list?

context_modification_mods_list ::= context_modification*

context_modification ::= WITH_COMMAND LEFT_BRACE context_mod_list RIGHT_BRACE
                       | WITH_COMMAND context_modification_arg

context_modification_arg ::= scheme_expression /*embedded_scm | MUSIC_IDENTIFIER*/

context_mod_list ::= (context_mod | context_mod_arg)*


context_mod_arg ::= scheme_expression /*embedded_scm*/
                  | composite_music

context_def_mod ::= CONSISTS_COMMAND
                  | REMOVE_COMMAND
                  | ACCEPTS_COMMAND
                  | DEFAULTCHILD_COMMAND
                  | DENIES_COMMAND
                  | ALIAS_COMMAND
                  | TYPE_COMMAND
                  | DESCRIPTION_COMMAND
                  | NAME_COMMAND

context_mod ::= property_operation
              | context_def_mod string_lit
              | context_def_mod SYMBOL
              | context_def_mod scheme_expression /*embedded_scm*/

context_def_spec_block ::= CONTEXT_COMMAND LEFT_BRACE context_def_spec_body RIGHT_BRACE


context_def_spec_body ::= (context_mod | context_modification| context_mod_arg)*

grob_prop_spec ::= symbol_list_rev

grob_prop_path ::= grob_prop_spec
                 | grob_prop_spec property_path

context_prop_spec ::= symbol_list_rev

simple_revert_context ::= symbol_list_part

music_property_def ::= OVERRIDE_COMMAND grob_prop_path EQUALS scalar
                     | REVERT_COMMAND simple_revert_context property_path
                     | SET_COMMAND context_prop_spec EQUALS scalar
                     | UNSET_COMMAND context_prop_spec

str ::= string_lit
      | SYMBOL
      | full_markup

simple_string ::= string_lit
                | SYMBOL
                | scheme_expression

scalar ::= scheme_expression
         | music_assign
         | pitch_or_music
         | scheme_identifier_lily
         | bare_number
         | MINUS bare_number
         | str
         | symbol_list_part_bare DOT property_path
         | symbol_list_part_bare COMMA property_path
         | command

event_chord ::= simple_element post_events
              | CHORD_REPETITION optional_notemode_duration post_events
              | MULTI_MEASURE_REST optional_notemode_duration post_events
              | tempo_event
              | note_chord_element

note_chord_element ::= chord_body optional_notemode_duration post_events

chord_body ::= SMALLER chord_body_elements GREATER
             | FIGURE_OPEN figure_list FIGURE_CLOSE

chord_body_elements ::= chord_body_element*

chord_body_element ::= pitch_or_tonic_pitch exclamations questions octave_check? slur? post_events
                     | DRUM_PITCH post_events
                     | scheme_expression /*music_function_call | MUSIC_IDENTIFIER | embedded_scm*/
                     | post_event

post_event ::= post_event_nofinger
             | MINUS fingering

post_event_nofinger ::= direction_less_event
                      | script_dir scheme_expression /*music_function_call*/
                      | HYPHEN
                      | EXTENDER
                      | script_dir direction_reqd_event
                      | script_dir direction_less_event
                      | HAT fingering
                      | UNDERSCORE fingering

header_block ::= HEADER_COMMAND LEFT_BRACE header_block_body RIGHT_BRACE

header_block_body ::= (assignment | scheme_expression | SCM_START)*

assignment ::= assignment_id (DOT property_path)? EQUALS identifier_init
             | markup_mode_word EQUALS identifier_init
             {pin=2}

assignment_id ::= string_lit | SYMBOL

identifier_init ::= identifier_init_nonumber
                  | number_expression
                  | symbol_list_part_bare DOT property_path
                  | symbol_list_part_bare COMMA property_path
                  | post_event_nofinger post_event*

identifier_init_nonumber ::= header_block
                           | score_block
                           | book_block
                           | bookpart_block
                           | output_def
                           | context_def_spec_block
                           | music_assign
                           | pitch_or_music
                           | fraction
                           | string_lit
                           | scheme_expression /*embedded_scm*/
                           | partial_markup
                           | full_markup_list
                           | context_modification
                           | partial_function ETC_COMMAND

partial_function ::= ( OVERRIDE_COMMAND grob_prop_path EQUALS
                     | SET_COMMAND context_prop_spec EQUALS
                     | REPEAT_COMMAND simple_string unsigned_integer
                     | REPEAT_COMMAND simple_string
                     )*
                     (scheme_expression | script_dir markup_mode? scheme_expression?)

property_path ::= symbol_list_rev

symbol_list_rev ::= symbol_list_part ((DOT | COMMA) symbol_list_part)*

symbol_list_part ::= symbol_list_part_bare
                   | scheme_expression

symbol_list_part_bare ::= SYMBOL
                        | symbol_list_element

symbol_list_element ::= string_lit
                      | unsigned

score_block ::= SCORE_COMMAND LEFT_BRACE score_body RIGHT_BRACE

score_body ::= score_items /* TODO parser recovery? error* */

score_item ::= scheme_expression
             | music
             | output_def

score_items ::= score_item* header_block

book_block ::= BOOK_COMMAND LEFT_BRACE book_body RIGHT_BRACE

book_body ::= (scheme_identifier_lily | command)? /*BOOK_IDENTIFIER*/ (
              paper_block
            | bookpart_block
            | score_block
            | composite_music
            | full_markup
            | full_markup_list
            | SCM_START /*SCM_TOKEN*/
            | scheme_expression /*embedded_scm_active*/
            | header_block
//            TODO parser recovery?
//            | error
            )*

bookpart_block ::= BOOKPART_COMMAND LEFT_BRACE bookpart_body RIGHT_BRACE

bookpart_body ::= (scheme_identifier_lily | command)? /*BOOK_IDENTIFIER*/ (
                  paper_block
                | score_block
                | composite_music
                | full_markup
                | full_markup_list
                | SCM_START /*SCM_TOKEN*/
                | scheme_expression /*embedded_scm_active*/
                | header_block
//                TODO parser recovery?
//                | error
                )*

paper_block ::= output_def

output_def ::= output_def_body

output_def_head ::= PAPER_COMMAND
                  | MIDI_COMMAND
                  | LAYOUT_COMMAND

output_def_head_with_mode_switch ::= output_def_head

output_def_body ::= output_def_head_with_mode_switch LEFT_BRACE
                  ( assignment
                  | scheme_expression /*embedded_scm_active*/
                  | SCM_START
                  | music_or_context_def
//                  TODO parser recovery?
//                  | error
                  )+ RIGHT_BRACE

music_or_context_def ::= music_assign
                       | context_def_spec_block

post_events ::= post_event*

direction_less_event ::= string_number_event
                       | scheme_identifier_lily /*EVENT_IDENTIFIER*/
                       | tremolo_type
                       | scheme_expression /*event_function_event*/
                       | command

direction_reqd_event ::= gen_text_def
                       | script_abbreviation

octave_check ::= EQUALS quotes

slur ::= LEFT_PAREN | RIGHT_PAREN

quotes ::= sub_quotes | sup_quotes

erroneous_quotes ::= quotes?

sup_quotes ::= SINGLE_QUOTE+

sub_quotes ::= COMMA+

steno_pitch ::= SYMBOL /*NOTENAME_PITCH*/ quotes*

steno_tonic_pitch ::= SYMBOL /*TONICNAME_PITCH*/ quotes*

pitch ::= steno_pitch
        | (scheme_identifier_lily | command) /*PITCH_IDENTIFIER*/ quotes*

pitch_or_tonic_pitch ::= pitch
                       | steno_tonic_pitch

gen_text_def ::= full_markup
               | string_lit
               | SYMBOL
               | scheme_expression /*embedded_scm*/

string_number_event ::= e_unsigned

fingering ::= unsigned

script_abbreviation ::= HAT
                      | PLUS
                      | MINUS
                      | EXCLAMATION_MARK
                      | GREATER
                      | DOT
                      | UNDERSCORE

script_dir ::= UNDERSCORE
             | HAT
             | MINUS

optional_notemode_duration ::= duration?

steno_duration ::= unsigned dots
                 | (scheme_identifier_lily | command) /*DURATION_IDENTIFIER*/ dots

duration ::= steno_duration multipliers

dots ::= DOT*

multiplier_scm ::= scheme_identifier_lily /*NUMBER_IDENTIFIER*/
                 | command
                 | scheme_expression /*embedded_scm_bare*/

multipliers ::= (STAR (unsigned | fraction | multiplier_scm))*

tremolo_type ::= COLON unsigned?

bass_number ::= unsigned
              | string_lit
              | SYMBOL
              | full_markup
              | scheme_expression /*embedded_scm_bare*/

bass_figure ::= (UNDERSCORE | bass_number)
              ( RIGHT_BRACKET
              | FIGURE_ALTERATION_EXPR
              | figured_bass_modification
              )*

figured_bass_modification ::= ESCAPED_PLUS
                            | ESCAPED_EXCLAMATION
                            | SLASH
                            | ESCAPED_BACKSLASH

br_bass_figure ::= bass_figure
                 | LEFT_BRACKET bass_figure

figure_list ::= br_bass_figure*

pitch_or_music ::= pitch exclamations questions octave_check? duration? erroneous_quotes slur? REST_COMMAND? post_events
                 | new_chord post_events

simple_element ::= DRUM_PITCH optional_notemode_duration
                 | RESTNAME optional_notemode_duration

lyric_element ::= full_markup
                | SYMBOL
                | string_lit
                | scheme_expression /*LYRIC_ELEMENT*/

lyric_element_music ::= lyric_element optional_notemode_duration post_events

new_chord ::= steno_tonic_pitch duration?
            | steno_tonic_pitch optional_notemode_duration chord_separator chord_items

chord_items ::= chord_item*

chord_separator ::= COLON
                  | HAT
                  | SLASH PLUS? steno_tonic_pitch

chord_item ::= chord_separator
             | step_numbers
             | CHORD_MODIFIER

step_numbers ::= step_number (DOT step_number)*

step_number ::= unsigned (PLUS | MINUS)?

tempo_range ::= unsigned_integer (MINUS unsigned_integer)?

unsigned_integer ::= unsigned
                   | scheme_expression /*embedded_scm*/

exclamations ::= EXCLAMATION_MARK*

questions ::= QUESTION_MARK*

unsigned ::= digit+

e_unsigned ::= BACKSLASH unsigned

fraction ::= unsigned SLASH unsigned

int ::= MINUS? unsigned

real ::= int DOT digit+

number_expression ::= number_term ((PLUS | MINUS) number_term)*

number_term ::= number_factor
              | number_factor STAR number_factor
              | number_factor SLASH number_factor

number_factor ::= MINUS* bare_number

bare_number ::= bare_number_common
              | unsigned (scheme_identifier_lily | command)?

bare_number_common ::= real
                     | (scheme_identifier_lily | command)
                     | real (scheme_identifier_lily | command)

partial_markup ::= markup_mode scheme_expression /*markup_partial_function*/ ETC_COMMAND

full_markup ::= markup_mode markup_top
              | markup_mode_word

full_markup_list ::= MARKUPLIST_COMMAND markup_list

markup_mode ::= MARKUP_COMMAND

markup_mode_word ::= markup_mode markup_word

markup_word ::= string_lit
              | SYMBOL

markup_top ::= markup_list
             | markup_head_1_list simple_markup
             | simple_markup_noword

markup_list ::= markup_composed_list
              | markup_uncomposed_list

markup_uncomposed_list ::= markup_braced_list
                         | markup_command_list
                         | scheme_expression scheme_identifier_lily /* markup_scm MARKUPLIST_IDENTIFIER*/
                         | SCORELINES_COMMAND LEFT_BRACE score_body RIGHT_BRACE

markup_composed_list ::= markup_head_1_list markup_uncomposed_list

markup_braced_list ::= LEFT_BRACE markup_braced_list_body RIGHT_BRACE

markup_braced_list_body ::= (markup | markup_list)*

markup_command_list ::= scheme_expression /*MARKUP_LIST_FUNCTION markup_command_list_arguments*/

markup_head_1_item ::= scheme_expression /*MARKUP_FUNCTION "markup?" markup_command_list_arguments*/

markup_head_1_list ::= markup_head_1_item+

simple_markup ::= markup_word
                | simple_markup_noword

simple_markup_noword ::= SCORE_COMMAND LEFT_BRACE score_body RIGHT_BRACE
                       | scheme_expression (scheme_identifier_lily | command)? /* MARKUP_FUNCTION markup_command_basic_arguments | markup_scm MARKUP_IDENTIFIER*/

markup ::= markup_head_1_list simple_markup
         | simple_markup

// old lilypond
//base_expression ::= expression | braced_expression | scheme_expression
//
//command ::= BACKSLASH WORD
//
//braced_expression ::= LEFT_BRACE unit* RIGHT_BRACE {pin=3}
//
//expression ::= unit+
//
//unit ::= command
//  | DIGIT
//  | DOT
//  | COMMA
//  | SINGLE_QUOTE
//  | TILDE
//  | BAR
//  | SLASH
//  | BACKSLASH
//  | COLON
//  | UNDERSCORE
//  | PLUS
//  | MINUS
//  | STAR
//  | HAT
//  | AMPERSAND
//  | QUESTION_MARK
//  | EXCLAMATION_MARK
//  | EQUALS
//  | LEFT_BRACE
//  | RIGHT_BRACE
//  | LEFT_BRACKET
//  | RIGHT_BRACKET
//  | LEFT_PAREN
//  | RIGHT_PAREN
//  | MULTI_VOICE_START
//  | MULTI_VOICE_END
//  | SMALLER
//  | GREATER
//  | string_lit
//  | WORD

string_lit ::= QUOTE (STRING_LITERAL_CHAR | ESCAPED_QUOTE | ESCAPED_BACKSLASH)* QUOTE

// TODO implement https://www.scheme.com/tspl2d/grammar.html
// Scheme parser has to be implemented here. Language injection is not possible because of nesting (LilyPond in Scheme and vice versa)
// and references from/to both languages.
scheme_expression ::= scheme_start scheme_expression_internal+

scheme_start ::= SCM_START | SCM_START_DOLLAR

scheme_expression_internal ::= scm_function | scm_unit | SCM_BLOCK_COMMENT | SCM_LINE_COMMENT | scm_lily

scheme_identifier_lily ::= scheme_start | SCM_IDENTIFIER

scm_function ::= SCM_BACKTICK? (SCM_VECTOR_OPEN | SCM_LEFT_PAREN) scheme_expression_internal* SCM_RIGHT_PAREN

scm_id ::= (SCM_IDENTIFIER | SCM_PLUS | SCM_MINUS | SCM_SLASH | SCM_STAR)

scm_unit ::= SCM_COMMA
  | SCM_SINGLE_QUOTE
  | SCM_DOT
  | string_lit
  | SCM_SMALLER
  | SCM_GREATER
  | SCM_QUESTION_MARK
  | SCM_EXCLAMATION_MARK
  | SCM_EQUALS
  | SCM_AT
  | SCM_TRUE
  | SCM_FALSE
  | SCM_CHAR_START
  | ((SCM_HASH | SCM_SINGLE_QUOTE)? (scm_number | scm_id) (SCM_QUESTION_MARK | SCM_EXCLAMATION_MARK)?)

scm_number ::= SCM_MINUS? SCM_DIGIT+

scm_lily ::= SCM_LILY_START (toplevel_expression /*base_expression*/ | BLOCK_COMMENT | LINE_COMMENT)* SCM_CONTINUE


// more complicated version that has some problems (how to define `_6` in `\addScript _6 { a b c }`?)
//expression ::= command | assignment | multi_voice | music_line | time_signature | scheme_expression | IDENTIFIER | STRING_LITERAL
//
//assignment ::= IDENTIFIER EQUALS expression {pin=2}
//
//multi_voice ::= MULTI_VOICE_START expression* MULTI_VOICE_END {pin=3}
//
//music_line ::= (note | SLASH | chord | command | BAR)+
//
//time_signature ::= DIGIT+ SLASH DIGIT+ {pin=2}
//
//chord ::= CHORD_START (command | note)* CHORD_END modifiers? {pin=3}
//
//note ::= (PLUS | MINUS)? IDENTIFIER modifiers? (COLON SLASH? chord_mode_augmentation)?
//
//modifiers ::= (octave_modifier | duration_modifier | articulation | TILDE | LEFT_PAREN | RIGHT_PAREN | LEFT_BRACKET | RIGHT_BRACKET | PLUS | MINUS | SLASH | STRING_LITERAL | command)+
//
//duration_modifier ::= DIGIT DOT?
//
//octave_modifier ::= EQUALS? (SINGLE_QUOTE+ | COMMA+)
//
//articulation ::= MINUS (HAT | PLUS | MINUS | EXCLAMATION_MARK | CHORD_END | DOT | UNDERSCORE)
//
//chord_mode_augmentation ::= (IDENTIFIER | DIGIT | DOT | PLUS | MINUS | HAT | UNDERSCORE)+